name: Daily Check-In

on:
  schedule:
    - cron: "5 16 * * *" # 00:05 UTC+8
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Run Program
        run: go run cmd/hoyo-daily/main.go

  keep-alive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
